config/routes.rb
require 'sidekiq/web'

GitlabCi::Application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resource :help

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status, to: 'projects#badge'
      get :integration
      post :build
    end

    resource :charts, only: [:show]

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :web_hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end
  end

  resource :user_sessions

  namespace :admin do
    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        put :assign_all
      end
    end

    resources :projects do
      resources :runner_projects
    end
  end

  root :to => 'projects#index'
end

app/models/build.rb
# == Schema Information
#
# Table name: builds
#
#  id          :integer          not null, primary key
#  project_id  :integer
#  ref         :string(255)
#  status      :string(255)
#  finished_at :datetime
#  trace       :text
#  created_at  :datetime
#  updated_at  :datetime
#  sha         :string(255)
#  started_at  :datetime
#  tmp_file    :string(255)
#  before_sha  :string(255)
#  push_data   :text
#  runner_id   :integer
#

class Build < ActiveRecord::Base
  belongs_to :project
  belongs_to :runner

  serialize :push_data

  attr_accessible :project_id, :ref, :sha, :before_sha,
    :status, :finished_at, :trace, :started_at, :push_data, :runner_id, :project_name, :coverage

  validates :before_sha, presence: true
  validates :sha, presence: true
  validates :ref, presence: true
  validates :status, presence: true
  validate :valid_commit_sha
  validates :coverage, numericality: true, allow_blank: true

  scope :running, ->() { where(status: "running") }
  scope :pending, ->() { where(status: "pending") }
  scope :success, ->() { where(status: "success") }
  scope :failed, ->() { where(status: "failed")  }
  scope :uniq_sha, ->() { select('DISTINCT(sha)') }

  def self.last_month
    where('created_at > ?', Date.today - 1.month)
  end

  def self.first_pending
    pending.where(runner_id: nil).order('created_at ASC').first
  end

  def self.create_from(build)
    new_build = build.dup
    new_build.status = :pending
    new_build.runner_id = nil
    new_build.save
  end

  state_machine :status, initial: :pending do
    event :run do
      transition pending: :running
    end

    event :drop do
      transition running: :failed
    end

    event :success do
      transition running: :success
    end

    event :cancel do
      transition [:pending, :running] => :canceled
    end

    after_transition :pending => :running do |build, transition|
      build.update_attributes started_at: Time.now
    end

    after_transition any => [:success, :failed, :canceled] do |build, transition|
      build.update_attributes finished_at: Time.now
      project = build.project

      if project.web_hooks?
        WebHookService.new.build_end(build)
      end

      if project.email_notification?
        if build.status.to_sym == :failed || !project.email_only_broken_builds
          NotificationService.new.build_ended(build)
        end
      end

      if project.coverage_enabled?
        build.update_coverage
      end
    end

    state :pending, value: 'pending'
    state :running, value: 'running'
    state :failed, value: 'failed'
    state :success, value: 'success'
    state :canceled, value: 'canceled'
  end

  def valid_commit_sha
    if self.sha =~ /\A00000000/
      self.errors.add(:sha, " cant be 00000000 (branch removal)")
    end
  end

  def compare?
    gitlab? && before_sha
  end

  def gitlab?
    project.gitlab?
  end

  def ci_skip?
    !!(git_commit_message =~ /(\[ci skip\])/)
  end

  def git_author_name
    commit_data[:author][:name] if commit_data && commit_data[:author]
  end

  def git_author_email
    commit_data[:author][:email] if commit_data && commit_data[:author]
  end

  def git_commit_message
    commit_data[:message] if commit_data
  end

  def short_before_sha
    before_sha[0..8]
  end

  def short_sha
    sha[0..8]
  end

  def trace_html
    html = Ansi2html::convert(trace) if trace.present?
    html ||= ''
  end

  def started?
    !pending? && !canceled? && started_at
  end

  def active?
    running? || pending?
  end

  def complete?
    canceled? || success? || failed?
  end

  def commands
    project.scripts
  end

  def commit_data
    push_data[:commits].each do |commit|
      return commit if commit[:id] == sha
    end
  rescue
    nil
  end

  # Build a clone-able repo url
  # using http and basic auth
  def repo_url
    auth = "gitlab-ci-token:#{project.token}@"
    url = project.gitlab_url + ".git"
    url.sub(/^https?:\/\//) do |prefix|
      prefix + auth
    end
  end

  def timeout
    project.timeout
  end

  def allow_git_fetch
    project.allow_git_fetch
  end

  def project_name
    project.name
  end

  def project_recipients
    recipients = project.email_recipients.split(' ')
    recipients << git_author_email if project.email_add_committer?
    recipients.uniq
  end

  def duration
    if started_at && finished_at
      finished_at - started_at
    elsif started_at
      Time.now - started_at
    end
  end

  def update_coverage
    coverage = extract_coverage(trace, project.coverage_regex)

    if coverage.is_a? Numeric
      update_attributes(coverage: coverage)
    end
  end

  def extract_coverage(text, regex)
    begin
      matches = text.gsub(Regexp.new(regex)).to_a.last
      coverage = matches.gsub(/\d+(\.\d+)?/).first

      if coverage.present?
        coverage.to_f
      end
    rescue => ex
      # if bad regex or something goes wrong we dont want to interrupt transition
      # so we just silentrly ignore error for now
    end
  end
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_filter :authenticate_user!, except: [:status]
  before_filter :project
  before_filter :authorize_access_project!, except: [:status]
  before_filter :build, except: [:status, :show]

  def show
    if params[:id] =~ /\A\d+\Z/
      @build = build
    else
      # try to find build by sha
      build = build_by_sha

      if build
        # Redirect from sha to build with id
        redirect_to project_build_path(build.project, build)
        return
      end
    end

    raise ActiveRecord::RecordNotFound unless @build

    @builds = project.builds.where(sha: @build.sha).order('id DESC')
    @builds = @builds.where("id not in (?)", @build.id).page(params[:page]).per(20)

    respond_to do |format|
      format.html
      format.json {
        render json: @build.to_json(methods: :trace_html)
      }
    end
  end

  def retry
    build = project.builds.create(
      sha: @build.sha,
      before_sha: @build.before_sha,
      push_data: @build.push_data,
      ref: @build.ref
    )

    redirect_to project_build_path(project, build)
  end

  def status
    @build = build_by_sha

    render json: @build.to_json(only: [:status, :id, :sha, :coverage])
  end

  def cancel
    @build.cancel

    redirect_to project_build_path(@project, @build)
  end

  protected

  def project
    @project = Project.find(params[:project_id])
  end

  def build
    @build ||= project.builds.find_by(id: params[:id])
  end

  def build_by_sha
    project.builds.where(sha: params[:id]).last
  end
end

app/views/builds/_build.html.haml
%tr.build.alert{class: build_status_alert_class(build)}
  %td.status
    = build.status

  %td.build-link
    = link_to build_url(build) do
      %strong #{build.short_sha}

  %td.build-message
    %span= truncate(build.git_commit_message, length: 50)

  %td.build-branch
    - unless @ref
      %span
        = link_to build.ref, project_path(@project, ref: build.ref)

  %td.duration
    - if build.duration
      #{distance_of_time_in_words build.duration}

  %td.timestamp
    - if build.finished_at
      %span #{time_ago_in_words build.finished_at} ago

  - if build.project.coverage_enabled?
    %td.coverage
      - if build.coverage
        #{build.coverage}%

app/views/builds/show.html.haml
%h4.page-title
  = @project.name
  .pull-right
    = link_to edit_project_path(@project), class: "btn btn-default btn-small" do
      %i.icon-edit.icon-white
      Edit Project

%p
  = link_to project_path(@project) do
    &larr; Back to project builds
%hr

.row
  .col-md-9
    .build-head.alert{class: build_status_alert_class(@build)}
      %h4
        Build for commit
        %code #{@build.short_sha}
        from

        = link_to project_path(@build.project, ref: @build.ref) do
          %span.label.label-primary= "#{@build.ref}"

        - if @build.duration
          .pull-right
            %span
              %i.icon-time
              #{distance_of_time_in_words @build.duration}

      .clearfix
        = @build.status
        .pull-right
          = @build.updated_at.stamp('19:00 Aug 27')



    .clearfix
      - if @build.active?
        .autoscroll-container.pull-right
          %button.btn.btn-default.btn-sm#autoscroll-button{:type => "button", :data => {:state => 'disabled'}} enable autoscroll
        .clearfix
    %pre.trace#build-trace
      %code.bash
        = preserve do
          = raw @build.trace_html

  .col-md-3
    - if @build.coverage
      .build-widget
        %h4.title
          Test coverage
        %h1 #{@build.coverage}%

    .build-widget
      %h4.title
        Build
        .pull-right
          - if @build.active?
            = link_to "Cancel", cancel_project_build_path(@project, @build), class: 'btn btn-sm btn-danger'
          - else
            = link_to "Retry", retry_project_build_path(@project, @build), class: 'btn btn-sm btn-primary', method: :post

      - if @build.duration
        %p
          %span.attr-name Duration:
          #{distance_of_time_in_words @build.duration}
      %p
        %span.attr-name Created:
        #{time_ago_in_words(@build.created_at)} ago
      - if @build.finished_at
        %p
          %span.attr-name Finished:
          #{time_ago_in_words(@build.finished_at)} ago
      %p
        %span.attr-name Runner:
        - if @build.runner
          \##{@build.runner.id}

    .build-widget
      %h4.title
        Commit
        .pull-right
          %small #{build_commit_link @build}

      - if @build.compare?
        %p
          %span.attr-name Compare:
          #{build_compare_link @build}
      %p
        %span.attr-name Branch:
        #{build_ref_link @build}
      %p
        %span.attr-name Author:
        #{@build.git_author_name}
      %p
        %span.attr-name Message:
        #{@build.git_commit_message}

    - if @builds.present?
      .build-widget
        %h4.title #{pluralize(@builds.count, "other build")} for #{@build.short_sha}:
        %table.builds
          - @builds.each_with_index do |build, i|
            %tr.build.alert{class: build_status_alert_class(build)}
              %td
                = link_to build_url(build) do
                  %span #{i+=1} &ndash; #{build.short_sha}
              %td.status= build.status


        = paginate @builds


:javascript
  new Build("#{build_url(@build)}", "#{@build.status}")