config/routes.rb
require 'sidekiq/web'

GitlabCi::Application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resource :help

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status, to: 'projects#badge'
      get :integration
      post :build
    end

    resource :charts, only: [:show]

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :web_hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end
  end

  resource :user_sessions

  namespace :admin do
    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        put :assign_all
      end
    end

    resources :projects do
      resources :runner_projects
    end
  end

  root :to => 'projects#index'
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                       :integer          not null, primary key
#  name                     :string(255)      not null
#  timeout                  :integer          default(1800), not null
#  scripts                  :text             not null
#  created_at               :datetime
#  updated_at               :datetime
#  token                    :string(255)
#  default_ref              :string(255)
#  gitlab_url               :string(255)
#  always_build             :boolean          default(FALSE), not null
#  polling_interval         :integer
#  public                   :boolean          default(FALSE), not null
#  ssh_url_to_repo          :string(255)
#  gitlab_id                :integer
#  allow_git_fetch          :boolean          default(TRUE), not null
#  email_recipients         :string(255)      default(""), not null
#  email_add_committer      :boolean          default(TRUE), not null
#  email_only_broken_builds :boolean          default(TRUE), not null
#

class Project < ActiveRecord::Base
  attr_accessible :name, :path, :scripts, :timeout, :token, :timeout_in_minutes,
    :default_ref, :gitlab_url, :always_build, :polling_interval,
    :public, :ssh_url_to_repo, :gitlab_id, :allow_git_fetch, :skip_refs,
    :email_recipients, :email_add_committer, :email_only_broken_builds, :coverage_regex

  has_many :builds, dependent: :destroy
  has_many :runner_projects, dependent: :destroy
  has_many :runners, through: :runner_projects
  has_many :web_hooks, dependent: :destroy

  #
  # Validations
  #
  validates_presence_of :name, :scripts, :timeout, :token, :default_ref, :gitlab_url, :ssh_url_to_repo, :gitlab_id

  validates_uniqueness_of :name

  validates :polling_interval,
    presence: true,
    if: ->(project) { project.always_build.present? }


  scope :public_only, ->() { where(public: true) }

  before_validation :set_default_values

  class << self
    def base_build_script
      <<-eos
git submodule update --init
ls -la
      eos
    end

    def parse(project_yaml)
      project = YAML.load(project_yaml)

      params = {
        name:                    project.name_with_namespace,
        gitlab_id:               project.id,
        gitlab_url:              project.web_url,
        scripts:                 Project.base_build_script,
        default_ref:             project.default_branch || 'master',
        ssh_url_to_repo:         project.ssh_url_to_repo,
        email_add_committer:     GitlabCi.config.gitlab_ci.add_committer,
        email_only_broken_builds: GitlabCi.config.gitlab_ci.all_broken_builds,
      }

      Project.new(params)
    end

    def from_gitlab(user, page, per_page, scope = :owned)
      opts = { private_token: user.private_token }
      opts[:per_page] = per_page if per_page.present?
      opts[:page]     = page     if page.present?

      projects = Network.new.projects(user.url, opts, scope)

      if projects
        projects.map { |pr| OpenStruct.new(pr) }
      else
        []
      end
    end

    def already_added?(project)
      where(gitlab_url: project.web_url).any?
    end

    def unassigned(runner)
      joins('LEFT JOIN runner_projects ON runner_projects.project_id = projects.id ' \
        "AND runner_projects.runner_id = #{runner.id}").
      where('runner_projects.project_id' => nil)
    end
  end

  def set_default_values
    self.token = SecureRandom.hex(15) if self.token.blank?
  end

  def gitlab?
    gitlab_url.present?
  end

  def status
    last_build.status if last_build
  end

  def broken?
    last_build.failed? || last_build.canceled? if last_build
  end

  def success?
    last_build.success? if last_build
  end

  def broken_or_success?
    broken? || success?
  end

  def last_build
    builds.last
  end

  def last_build_date
    last_build.try(:created_at)
  end

  def human_status
    status
  end

  def last_build_for_sha(sha)
    builds.where(sha: sha).order('id DESC').limit(1).first
  end

  def tracked_refs
    @tracked_refs ||= default_ref.split(",").map{|ref| ref.strip}
  end

  def valid_token? token
    self.token && self.token == token
  end

  def no_running_builds?
    # Get running builds not later than 3 days ago to ignore hangs
    builds.running.where("updated_at > ?", 3.days.ago).empty?
  end

  def email_notification?
    email_add_committer || email_recipients.present?
  end

  def web_hooks?
    web_hooks.any?
  end

  # onlu check for toggling build status within same ref.
  def last_build_changed_status?
    ref = last_build.ref
    last_builds = builds.where(ref: ref).order('id DESC').limit(2)
    return false if last_builds.size < 2
    return last_builds[0].status != last_builds[1].status
  end

  def timeout_in_minutes
    timeout / 60
  end

  def timeout_in_minutes=(value)
    self.timeout = value.to_i * 60
  end

  def skip_ref?(ref_name)
    if skip_refs.present?
      skip_refs.delete(" ").split(",").include?(ref_name)
    else
      false
    end
  end

  def coverage_enabled?
    coverage_regex.present?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!, except: [:build, :badge, :index, :show]
  before_filter :project, only: [:build, :integration, :show, :badge, :edit, :update, :destroy]
  before_filter :authorize_access_project!, except: [:build, :gitlab, :badge, :index, :show, :new, :create]
  before_filter :authenticate_token!, only: [:build]
  before_filter :no_cache, only: [:badge]

  layout 'project', except: [:index, :gitlab]

  def index
    @projects = Project.public_only.page(params[:page]) unless current_user
  end

  def gitlab
    current_user.reset_cache if params[:reset_cache]
    @page = (params[:page] || 1).to_i
    @per_page = 100
    @gl_projects = current_user.gitlab_projects(@page, @per_page)
    @projects = Project.where(gitlab_id: @gl_projects.map(&:id)).order('name ASC')
    @total_count = @gl_projects.size
    @gl_projects.reject! { |gl_project| @projects.map(&:gitlab_id).include?(gl_project.id) }
  rescue
    @error = 'Failed to fetch GitLab projects'
  end

  def show
    unless @project.public
      unless current_user
        redirect_to(new_user_sessions_path(return_to: request.fullpath)) and return
      end

      unless current_user.can_access_project?(@project.gitlab_id)
        page_404 and return
      end
    end

    @ref = params[:ref]

    @builds = @project.builds
    @builds = @builds.where(ref: @ref) if @ref
    @builds = @builds.order('id DESC').page(params[:page]).per(20)
  end

  def integration
  end

  def create
    @project = CreateProjectService.new.execute(current_user, params[:project], project_url(":project_id"))

    if @project.persisted?
      redirect_to project_path(@project, show_guide: true), notice: 'Project was successfully created.'
    else
      redirect_to :back, alert: 'Cannot save project'
    end
  end

  def edit
  end

  def update
    if project.update_attributes(params[:project])
      redirect_to project, notice: 'Project was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    project.destroy
    Network.new.disable_ci(current_user.url, project.gitlab_id, current_user.private_token)

    redirect_to projects_url
  end

  def build
    @build = CreateBuildService.new.execute(@project, params.dup)

    if @build && @build.persisted?
      head 201
    else
      head 400
    end
  end

  # Project status badge
  # Image with build status for sha or ref
  def badge
    image = ImageForBuildService.new.execute(@project, params)

    send_file image.path, filename: image.name, disposition: 'inline'
  end

  protected

  def project
    @project ||= Project.find(params[:id])
  end

  def no_cache
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

app/views/projects/_form.html.haml
= form_for @project, html: { class: 'form-horizontal' } do |f|
  - if @project.errors.any?
    #error_explanation
      %p.lead= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      .alert.alert-error
        %ul
          - @project.errors.full_messages.each do |msg|
            %li= msg

  %fieldset
    %legend Build settings
    .form-group
      = f.label :scripts, 'Build steps', class: 'control-label'
      .col-sm-10
        = f.text_area :scripts, class: 'form-control', rows: 14, placeholder: "bundle exec rake spec"
        .bs-callout.bs-callout-info
          %p
            All lines will be concatenated in one file and executed.
            %br
            If you change the working directory or the environment in one line - it will affect the next lines too

    .form-group
      = label_tag nil, class: 'control-label' do
        Get code
      .col-sm-10
        %p Get recent application code using the following command:
        .radio
          = label_tag do
            = f.radio_button :allow_git_fetch, 'false'
            %strong git clone
            .light Slower but makes sure you have a clean dir before every build
        .radio
          = label_tag do
            = f.radio_button :allow_git_fetch, 'true'
            %strong git fetch
            .light Faster
    .form-group
      = f.label :timeout_in_minutes, 'Timeout', class: 'control-label'
      .col-sm-10
        = f.number_field :timeout_in_minutes, class: 'form-control', min: '0'
        .light per build in minutes


  %fieldset
    %legend Build Schedule
    .form-group
      = f.label :always_build, 'Schedule build', class: 'control-label'
      .col-sm-10
        .checkbox
          = f.label :always_build do
            = f.check_box :always_build
            %span.light Repeat last build after X hours if no builds
    .form-group
      = f.label :polling_interval, "Build interval", class: 'control-label'
      .col-sm-10
        = f.number_field :polling_interval, placeholder: '5', min: '0', class: 'form-control'
        .light In hours

  %fieldset
    %legend Project settings
    .form-group
      = f.label :default_ref, "Make tabs for the following branches", class: 'control-label'
      .col-sm-10
        = f.text_field :default_ref, class: 'form-control', placeholder: 'master, stable'
        .light You will be able to filter builds by the following branches
    .form-group
      = f.label :public, 'Public mode', class: 'control-label'
      .col-sm-10
        .checkbox
          = f.label :public do
            = f.check_box :public
            %span.light Anyone can see project and builds list
    .form-group
      = f.label :coverage_regex, "Test coverage parsing", class: 'control-label'
      .col-sm-10
        .input-group
          %span.input-group-addon /
          = f.text_field :coverage_regex, class: 'form-control', placeholder: '\(\d+.\d+\%\) covered'
          %span.input-group-addon /
        .light We will use this regular expression to find test coverage output in build trace. Leave blank if you want to disable this feature
        .bs-callout.bs-callout-info
          %p Below are examples of regex for existing tools:
          %ul
            %li
              Simplecov (Ruby) -
              %code \(\d+.\d+\%\) covered



  %fieldset
    %legend Email notification
    .form-group
      = f.label :email_recipients, "Recipients", class: 'control-label'
      .col-sm-10
        = f.text_field :email_recipients, class: 'form-control'
        .light Whitespace-separated list of recipient addresses
    .form-group
      .col-sm-2
      .col-sm-10
        .checkbox
          = f.label :email_add_committer do
            = f.check_box :email_add_committer
            %span Add committer to recipients list
    .form-group
      .col-sm-2
      .col-sm-10
        .checkbox
          = f.label :email_only_broken_builds do
            = f.check_box :email_only_broken_builds
            %span Send notification only for broken builds

  %fieldset
    %legend Advanced settings
    .form-group
      = f.label :name, class: 'control-label'
      .col-sm-10
        = f.text_field :name, class: 'form-control', placeholder: 'my-project'
    .form-group
      = f.label :gitlab_url, "GitLab url to project", class: 'control-label'
      .col-sm-10
        = f.text_field :gitlab_url, class: 'form-control', placeholder: 'http://gitlab.domain.com/project-slug'
    .form-group
      = f.label :gitlab_id, "GitLab project id", class: 'control-label'
      .col-sm-10
        = f.text_field :gitlab_id, class: 'form-control', placeholder: '17'
    .form-group
      = f.label :token, "CI token", class: 'control-label'
      .col-sm-10
        = f.text_field :token, class: 'form-control', placeholder: 'xEeFCaDAB89'
    .form-group
      = f.label :skip_refs, "Skip refs", class: 'control-label'
      .col-sm-10
        = f.text_field :skip_refs, class: 'form-control', placeholder: 'branch1, branch2'

  .form-actions
    = f.submit 'Save changes', class: 'btn btn-save'
    = link_to 'Cancel', projects_path, class: 'btn'
    - unless @project.new_record?
      = link_to 'Remove Project', project_path(@project), method: :delete, data: { confirm: 'Project will be removed. Are you sure?' }, class: 'btn btn-danger pull-right'

app/views/projects/_gitlab.html.haml
.clearfix.light
  .pull-left.fetch-status
    Fetched from GitLab (#{link_to current_user.url, current_user.url}) #{time_ago_in_words(current_user.sync_at)} ago.
    = link_to gitlab_projects_path(reset_cache: true), remote: true, class: 'sync-now btn btn-xs btn-default' do
      %i.icon-refresh
      Sync now
    %br

  .pull-right
    #{@total_count} projects, #{@projects.size} of them added to CI
%br

%table.table.projects-table
  %thead
    %tr
      %th ID
      %th Project Name
      %th Last build
      %th Access
      %th Builds

  = render @projects

  - @gl_projects.sort_by(&:name_with_namespace).each do |project|
    %tr.light
      %td
        \-
      %td
        = project.name_with_namespace
      %td
        %small Not added to CI
      %td
      %td
        - if Project.already_added?(project)
          %strong.cgreen
            Added
        - else
          = form_tag projects_path do
            = hidden_field_tag :project, project.to_yaml
            = submit_tag 'Add', class: 'btn btn-default btn-xs'

%ul.pagination.gitlab-projects-pagination
  - if @page > 1
    %li
      = link_to gitlab_projects_path(page: @page - 1), class: 'btn', remote: true do
        %i.icon-angle-left
        Previous
  &nbsp;
  - if @total_count == @per_page
    %li
      = link_to gitlab_projects_path(page: @page + 1), class: 'btn', remote: true do
        Next
        %i.icon-angle-right

:coffeescript
  $('.gitlab-projects-pagination').on 'ajax:before', ->
    $('.projects').html('<h1><i class="icon-spinner icon-spin"/></h1>')

app/views/projects/_public.html.haml
= content_for :title do
  %h3.project-title
    Public projects

- if @projects.present?
  .projects
    %table.table
      %tr
        %th ID
        %th Name
        %th Last build
        %th Access
        %th Builds
      = render @projects
  = paginate @projects
- else
  %h4 No public projects yet

app/views/projects/show.html.haml
= render 'shared/guide' if params[:show_guide].present?


%ul.nav.nav-tabs.append-bottom-20
  %li{class: ref_tab_class}
    = link_to 'All builds', project_path(@project)
  - @project.tracked_refs.each do |ref|
    %li{class: ref_tab_class(ref)}
      = link_to ref, project_path(@project, ref: ref)

  - if @ref && !@project.tracked_refs.include?(@ref)
    %li{class: 'active'}
      = link_to @ref, project_path(@project, ref: @ref)



- if @ref
  %p
    Paste build status image for #{@ref} with next link
    = link_to '#', class: 'badge-codes-toggle btn btn-default btn-xs' do
      Status Badge
    .badge-codes-block.bs-callout.bs-callout-info.hide
      %p
        Status badge for
        %span.label.label-info #{@ref}
        branch
      %div
        %label Markdown:
        = text_field_tag 'badge_md', markdown_badge_code(@project, @ref), readonly: true, class: 'form-control'
        %label Html:
        = text_field_tag 'badge_html', html_badge_code(@project, @ref), readonly: true, class: 'form-control'




%table.builds
  %thead
    %tr
      %th Status
      %th Commit
      %th Message
      %th Branch
      %th Duration
      %th Finished at
      - if @project.coverage_enabled?
        %th Coverage

  = render @builds

= paginate @builds
- if @builds.empty?
  .bs-callout
    %h4 No builds yet