config/routes.rb
require 'sidekiq/web'

GitlabCi::Application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resource :help

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status, to: 'projects#badge'
      get :integration
      post :build
    end

    resource :charts, only: [:show]

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :web_hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end
  end

  resource :user_sessions

  namespace :admin do
    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        put :assign_all
      end
    end

    resources :projects do
      resources :runner_projects
    end
  end

  root :to => 'projects#index'
end

app/views/layouts/_head.html.haml
%head
  %meta{charset: "utf-8"}
  %meta{content: "GitLab Continuous Integration", name: "description"}
  %title GitLab CI
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
  = favicon_link_tag 'favicon.ico'
  :erb
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

app/views/layouts/_nav.html.haml
.navbar.navbar-static-top.navbar-ci
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %i.icon-reorder

      = link_to 'GitLab CI', root_path, class: "navbar-brand"

    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if current_user && current_user.is_admin
          %li
            = link_to admin_runners_path do
              Runners
          %li
            = link_to admin_projects_path do
              Projects
        %li
          = link_to 'Help', help_path

      %ul.nav.navbar-nav.pull-right
        - if current_user
          %li
            = link_to user_sessions_path do
              .profile-holder
                = image_tag gravatar_icon(current_user.email, 24)
                %span= current_user.name
          %li
            = link_to user_sessions_path, class: "logout", method: :delete do
              %i.icon-signout
              Logout
        - else
          %li
            = link_to 'Login', new_user_sessions_path(return_to: request.fullpath)

app/views/layouts/project.html.haml
!!! 5
%html{ lang: "en"}
  = render 'layouts/head'
  %body{ :'data-page' => body_data_page }
    = render 'layouts/nav'
    = render 'layouts/info'
    .container
      %h3.project-title
        = @project.name
        - if @project.public
          %small
            %i.icon-globe
            Public

        - if @project.gitlab_url.present?
          .pull-right
            = link_to 'View on GitLab', @project.gitlab_url, class: 'btn btn-small'
    %hr
    .container
      .row
        - if current_user
          .col-md-2.append-bottom-20
            %ul.nav.nav-pills.nav-stacked.project-menu
              = nav_link path: 'projects#show' do
                = link_to project_path(@project) do
                  %i.icon-list-alt
                  Builds
                  %small.pull-right= @project.builds.count
              = nav_link path: 'charts#show' do
                = link_to project_charts_path(@project) do
                  %i.icon-bar-chart
                  Charts
              = nav_link path: 'projects#integration' do
                = link_to integration_project_path(@project) do
                  %i.icon-wrench
                  Integration
              = nav_link path: 'web_hooks#index' do
                = link_to project_web_hooks_path(@project) do
                  %i.icon-link
                  Web Hooks
              = nav_link path: 'projects#edit' do
                = link_to edit_project_path(@project) do
                  %i.icon-edit
                  Settings
        .col-md-10
          = yield